### ISSUE TITLE
error in scenario "The Triad - Part 2"

### ISSUE THREAD

**Issue by AncientGeneral** [project-ethea/After_the_Storm#17]
![screen](https://user-images.githubusercontent.com/20964929/42165665-6a405d74-7e11-11e8-867b-970c465d5818.png)

**Comment by shikadiqueen** [comment]
I didn't expect anyone to test AtS on 1.14 before I could get to it myself, but thanks for the report.

Do note that while I don't terribly mind people playtesting on 1.14 before I get to test it myself (and wire in several gameplay changes slated for version 0.10), you're pretty much *required* to have already played the campaign on 1.12 from start to beginning so that you're able to report all bugs you come across, including potentially subtle misbehaviour in cutscenes.
